services:
  web:
      build: ./nginx
      container_name: nginx-server
      volumes:
        - ./nginx/logs:/var/log/nginx
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./app:/usr/share/nginx/html
      ports:
        - "8080:80"
      environment:
        - NGINX_PORT=80

  fail2ban:
    image: lscr.io/linuxserver/fail2ban:latest
    container_name: fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host # Indispensable pour bannir sur l'hôte
    environment:
      - PUID=1000 # Ton ID utilisateur (tape 'id' dans ton terminal pour vérifier)
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./fail2ban/config:/config # Toute la config (jails, filters) est ici
      - ./nginx/logs:/remotelogs/nginx:ro # On monte les logs Nginx ici
    restart: unless-stopped