services:
  web:
      build: ./nginx
      container_name: nginx-server
      volumes:
        - ./nginx/logs:/var/log/nginx
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./app:/usr/share/nginx/html
      ports:
        - 8080:80
      environment:
        - NGINX_PORT=80

  fail2ban:
    image: lscr.io/linuxserver/fail2ban:latest
    container_name: fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host # Accorde les droit sur le reseau (lui permet de modifier les régles firewall pour ban ip)
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./fail2ban/config:/config/fail2ban # Toute la config (jails, filters) est ici
      - ./fail2ban/log:/config/log/fail2ban
      - ./nginx/logs:/remotelogs/nginx:ro # On monte les logs Nginx ici
    restart: unless-stopped