# Section Main (Obligatoire)
user nginx;
worker_processes auto;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Logs formatés pour Fail2Ban
    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log warn; # Fail2Ban lit ici les "limiting requests"

    # Rate Limiting
    limit_req_zone $binary_remote_addr zone=zone_main:10m rate=5r/s;
    limit_req_zone $binary_remote_addr zone=zone_assets:10m rate=30r/s;

    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;

        location / {
            limit_req zone=zone_main burst=10 nodelay;
            index index.html;
        }

        location ~* ^/(img|scripts|font)/ {
            limit_req zone=zone_assets burst=200 nodelay;
            expires 30d;
            add_header Cache-Control "public, no-transform";
        }
    }
}