user nginx;
worker_processes auto;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Logs formatés pour Fail2Ban
    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log warn; # Fail2Ban lit ici les "limiting requests"

    # Rate Limiting
    # Définition des zones de limitation
    limit_req_zone $binary_remote_addr zone=zone_main:10m rate=5r/s;
    # → Limite chaque IP à 5 requêtes/seconde pour les pages principales
    
    limit_req_zone $binary_remote_addr zone=zone_assets:10m rate=30r/s;
    # → Limite chaque IP à 30 requêtes/seconde pour les fichiers statiques (images, scripts, polices)

    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;

        location / {
            # Application de la limitation sur le site principal
            limit_req zone=zone_main burst=10 nodelay;
            # → Autorise jusqu’à 10 requêtes supplémentaires en rafale sans délai avant blocage

            index index.html;
        }

        location ~* ^/(img|scripts|font)/ {
            # Application de la limitation sur les assets
            limit_req zone=zone_assets burst=200 nodelay;
            # → Autorise jusqu’à 200 requêtes supplémentaires en rafale pour les fichiers statiques
            
            expires 30d;
            add_header Cache-Control "public, no-transform";
        }
    }
}
